import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1761340056488 implements MigrationInterface {
    name = ' $npmConfigName1761340056488'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "name" character varying, "verificationCode" character varying, "verificationExpiresAt" TIMESTAMP, "resetPasswordCode" character varying, "resetPasswordExpiresAt" TIMESTAMP, "isLive" boolean NOT NULL DEFAULT false, "isVerified" boolean NOT NULL DEFAULT false, "avatar" character varying, "phone" character varying, "website" character varying, "country" character varying, "referral_code" character varying, "supportEmail" character varying, "supportPhone" character varying, "payoutOtp" character varying, "payoutOtpExpiresAt" TIMESTAMP, "pendingPayoutId" character varying, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pageName" character varying NOT NULL, "checkout_settings" jsonb, "productType" character varying NOT NULL, "currency_collected" character varying NOT NULL, "currency" character varying NOT NULL, "access_code" character varying NOT NULL, "status" character varying NOT NULL, "source" character varying NOT NULL, "isFixedAmount" boolean NOT NULL, "paymentUrl" character varying NOT NULL, "currency_settled" character varying NOT NULL, "successmsg" character varying, "customLink" character varying, "dated" TIMESTAMP NOT NULL, "amount" character varying, "redirectLink" character varying, "CustomerCode" character varying NOT NULL, "description" character varying NOT NULL, "custompaymentUrl" character varying, "accountId" uuid, CONSTRAINT "PK_0f3fae8099b1cad5dee31f30cf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "beneficiaries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "beneficiary_id" character varying NOT NULL, "account_no" character varying NOT NULL, "routing" character varying NOT NULL, "dated" TIMESTAMP NOT NULL, "beneficiary_name" character varying NOT NULL, "beneficiary_address_1" character varying NOT NULL, "beneficiary_address_2" character varying, "beneficiary_city" character varying NOT NULL, "beneficiary_state" character varying NOT NULL, "beneficiary_country" character varying NOT NULL, "beneficiary_postal_code" character varying, "bank_name" character varying NOT NULL, "bank_address_1" character varying, "bank_address_2" character varying, "bank_city" character varying, "bank_state" character varying, "bank_country" character varying, "bank_postal_code" character varying, "swift_code" character varying, "transfer_type" character varying NOT NULL, "recipient_firstname" character varying, "recipient_lastname" character varying, "recipient_kyc" jsonb, "is_domiciliary" boolean NOT NULL DEFAULT false, "is_individual" boolean NOT NULL DEFAULT true, "account_id" character varying NOT NULL, "accountId" uuid, CONSTRAINT "PK_c9356d282dec80f7f12a9eef10a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_name" character varying NOT NULL, "businessId" character varying, "business_type" character varying, "bizAddress" character varying, "business_website" character varying, "checkout_settings" jsonb, "currencies" text array, "merchantCode" character varying, "superMerchantCode" character varying, "webhook_url" character varying, "settlementType" jsonb, "isVulaUser" boolean NOT NULL DEFAULT false, "is_identity_only" boolean NOT NULL DEFAULT false, "is_regular" boolean NOT NULL DEFAULT true, "is_otc" boolean NOT NULL DEFAULT false, "is_portco" boolean NOT NULL DEFAULT false, "is_tx" boolean NOT NULL DEFAULT false, "is_vc" boolean NOT NULL DEFAULT false, "isLive" boolean NOT NULL DEFAULT false, "FPR" jsonb, "YPEM" jsonb, "country" character varying NOT NULL, "currency" character varying NOT NULL, "account_no" character varying NOT NULL, "account_name" character varying NOT NULL, "bank_name" character varying NOT NULL, "bank_code" character varying, "bank_address" character varying, "swift_code" character varying, "sort_code" character varying, "routing_number" character varying, "iban" character varying, "is_domiciliary" boolean NOT NULL DEFAULT false, "userId" uuid NOT NULL, "dated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventname" character varying NOT NULL, "transtype" character varying NOT NULL, "total_amount" numeric(10,2) NOT NULL, "settled_amount" numeric(10,2) NOT NULL, "fee_charged" numeric(10,2) NOT NULL, "currency_settled" character varying NOT NULL, "dated" TIMESTAMP NOT NULL, "status" character varying NOT NULL, "initiator" character varying, "type" character varying NOT NULL, "transactionid" character varying NOT NULL, "narration" character varying NOT NULL, "balance_before" numeric(10,2) NOT NULL, "balance_after" numeric(10,2) NOT NULL, "channel" character varying, "beneficiary_bank" character varying, "email" character varying, "balanceType" character varying, "wallet_id" uuid NOT NULL, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "balances" jsonb, CONSTRAINT "REL_3758a15697c5d6964552b6a9d1" UNIQUE ("account_id"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "countries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "iso2" character varying NOT NULL, CONSTRAINT "UQ_fa1376321185575cf2226b1491d" UNIQUE ("name"), CONSTRAINT "UQ_9706e3c52695ce44a202f24c26b" UNIQUE ("iso2"), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "banks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "logo" character varying NOT NULL, "slug" character varying NOT NULL, "bank_code" character varying NOT NULL, "country" character varying NOT NULL, "active" boolean NOT NULL, "bank_name" character varying NOT NULL, CONSTRAINT "PK_3975b5f684ec241e3901db62d77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "payment_pages" ADD CONSTRAINT "FK_44b21a602350829a9924a796fbf" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD CONSTRAINT "FK_8bbd6f96144e2ff34c9f7e43be3" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_3758a15697c5d6964552b6a9d1c" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_3758a15697c5d6964552b6a9d1c"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP CONSTRAINT "FK_8bbd6f96144e2ff34c9f7e43be3"`);
        await queryRunner.query(`ALTER TABLE "payment_pages" DROP CONSTRAINT "FK_44b21a602350829a9924a796fbf"`);
        await queryRunner.query(`DROP TABLE "banks"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "beneficiaries"`);
        await queryRunner.query(`DROP TABLE "payment_pages"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
